/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pair with the server using a pairing token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description The unique identifier for the robot */
                        robot_id?: string;
                    };
                };
            };
            responses: {
                /** @description Paired successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description The token to be used for authenticated requests
                             * @example xj2bjzx8b1njk2n
                             */
                            pairing_token?: string;
                        };
                    };
                };
                /** @description Invalid robot ID */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Invalid robot ID */
                            error?: string;
                        };
                    };
                };
                /** @description Robot already paired */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Robot already paired */
                            error?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/robot/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new robot with the server */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description The unique identifier for the robot */
                        robot_id?: string;
                    };
                };
            };
            responses: {
                /** @description Registered successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Robot already registered */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Robot already registered */
                            error?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get server status */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Server status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Server is running */
                            status?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/command": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** get next command from server */
        get: {
            parameters: {
                query: {
                    /** @description The unique identifier for the robot */
                    robot_id: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Next command */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            Behavior?: components["schemas"]["Behavior"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/command/speak": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a speak command to the server */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description This is what I, the robot, will say. */
                        text?: string;
                        style?: components["schemas"]["Style"];
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            responses: {
                /** @description Command received */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Speak command received */
                            received_command?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/command/listenSilence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a command for the robot to listen until it detects silence */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        style?: components["schemas"]["Style"];
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            responses: {
                /** @description Command received */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example ListenUntilSilence command received */
                            received_command?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/command/listenKeyword": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a command for the robot to listen until it detects a keyword */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description The keyword to listen for */
                        keyword?: string;
                        style?: components["schemas"]["Style"];
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            responses: {
                /** @description Command received */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example ListenUntilKeyword command received */
                            received_command?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Behavior: {
            /** @description Type of behavior (e.g., nod, utterance, gaze) */
            type: string;
            /** @description Amplitude of the behavior (for nodding behavior) */
            amplitude?: number;
            /** @description Speed of the behavior (for nodding behavior) */
            speed?: number;
            /** @description Utterance text (for utterance behavior) */
            utterance?: string;
        };
        Style: {
            nodding?: {
                /** @description Whether to nod while speaking */
                enabled?: boolean;
                /** @description Frequency of nodding (nodding per second) */
                frequency?: number;
                /** @description Intensity of nodding */
                intensity?: number;
                /**
                 * @description Direction of nodding
                 * @enum {string}
                 */
                direction?: "up_down" | "left_right";
            };
            utterances?: {
                /** @description Whether to use verbal utterances */
                enabled?: boolean;
                /** @description Frequency of utterances */
                utterance_frequency?: number;
                /** @description Volume of utterances */
                utterance_volume?: number;
                /** @description List of utterances to use */
                utterance_list?: string[];
            };
            gaze?: {
                /** @description Whether to use gaze behavior */
                enabled?: boolean;
                /** @description Frequency of eye contact */
                eye_contact?: number;
                /** @description Frequency of gaze shifts */
                shift_gaze?: number;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
